substitutions:
  device_name: navien
  friendly_name: Navien
  tx_pin: GPIO6
  rx_pin: GPIO5

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  project:
    name: jhenkens.navien-atoms3-rs485base
    version: "1.0.0"

esp32:
  board: m5stack-atoms3
  variant: esp32s3
  framework:
    type: esp-idf

wifi:
  fast_connect: true
  ap:
    ssid: ${device_name} AP

packages:
  navien_base:
    url: https://github.com/jhenkens/esphome-navien
    ref: hardware-guide
    files: [esphome/navien-atoms3-base.yaml]
    refresh: 1d

dashboard_import:
  package_import_url: github://jhenkens/esphome-navien/esphome/navien-esphome-atoms3-lite-rs485base-esp32.yml@hardware-guide
  import_full_config: false
